### ISSUE TITLE
Ubicación de aventuras

### ISSUE THREAD

**Issue by Federico-G** [laucio/eclipsados#3]
Las aventuras deberían estar bien ubicadas. Ahora solo tienen una que es la de pruebas creo, pero de todas maneras no debería estar en la raíz del proyecto

https://github.com/laucio/eclipsados/blob/master/Juego.json

**Comment by laucio** [comment]
commit c3f32eafd46bd61dcebb8fdcc87d8cea114c731a

@Federico-G

**Comment by Federico-G** [comment]
En el commit nombrado no encuentro la solución. En master vi que tienen una carpeta Aventura que esta bien, pero también me encuentro con esto en la raiz
https://github.com/laucio/eclipsados/blob/master/Adventure.txt
