### ISSUE TITLE
Ubicación de bibliotecas 

### ISSUE THREAD

**Issue by Federico-G** [laucio/eclipsados#4]
Las bibliotecas deberían estar bien ubicadas. Ahora solo tienen una que es la de gson, pero de todas maneras no debería estar en la raíz del proyecto. Normalmente las mismas se ubican en una carpeta en la raiz llamada "lib"

**Comment by laucio** [comment]
#11 @Federico-G

**Comment by Federico-G** [comment]
No estaría encontrando la ubicación de las bibliotecas, como por ejemplo gson, ni la carpeta lib. Si vi el cambio en la configuracion de build de eclipse, pero no los archivos

**Comment by cordobafabian** [comment]
#11 Y #12
