### ISSUE TITLE
Uso de constantes

### ISSUE THREAD

**Issue by Federico-G** [laucio/eclipsados#5]
Hay varios lugares donde utilizan estos mismos atributos como String

https://github.com/laucio/eclipsados/blob/6345c93f3722cd79ede9228160fb399f843db4cb/src/source/Place.java#L8-L9

En Java se prefieren los enum por encima de las constantes. Nos brindan más flexibilidad.

Otro extra opcional es que si en varias clases usan estos, podrían armar una clase padre que maneje todo el tema de nombramiento

**Comment by laucio** [comment]
#9 
@Federico-G

**Comment by Federico-G** [comment]
En el PR nombrado no estoy encontrando ningun enum, ni nada por el estilo. Podrían indicarlo más especificamente? Gracias

**Comment by Gabrielbanegas94** [comment]
En este caso lo que necesitamos es  tener esos atributos en cada clase, para que las funciones de la biblioteca "gson" puedan crear los objetos correctamente.
Para ello hemos realizado una clase Thing que tiene estos atributos mencionados (name, gender y number) y el resto de la clases que los necesitan los heredan de esta superclase Thing.

**Comment by cordobafabian** [comment]
En este commit se crea la clase Thing mencionada
commit 4e2b1a6ae12744f49ef41773b3802fbf2373e793
