### ISSUE TITLE
Getters y setters

### ISSUE THREAD

**Issue by Federico-G** [laucio/eclipsados#6]
Construyan los getters y setters a medida que los necesiten

En la class Action por ejemplo, hay algunos getters y setters construidos sin ser usados en ningún lado

**Comment by laucio** [comment]
trabajado en commit 4f76f38f32b236d24e1e888dc10ee59f14d42938 y 1268cc9eff14dc5cb54adfd83c6dee2ebb34d51b

@Federico-G

**Comment by Federico-G** [comment]
👍
