### ISSUE TITLE
Objetos concretos antes que Strings

### ISSUE THREAD

**Issue by Federico-G** [laucio/eclipsados#8]
Les pongo uno de los casos como ejemplo

https://github.com/laucio/eclipsados/blob/6345c93f3722cd79ede9228160fb399f843db4cb/src/source/Location.java#L84

Si le digo que voy a borrar un Item, o algo con un objeto definido, debería recibir el mismo. En el caso de ejemplo deberia recibir un Item, y no un string

Fuera del issue en particular, no entiendo para que sirve ese método que elimina un objeto de todos los places

**Comment by laucio** [comment]
@Federico-G

**Comment by Federico-G** [comment]
👍
